---
name: Acme-PM-Dresden
version: 0.10
author: ~
abstract: ~
license: perl
requires:
  Class::MethodMaker: 0
  WWW::Mechanize: 0
  XML::Simple: 0
  perl: 5.6.1
build_requires:
  Test::More: 0
  Text::Diff: 0
provides:
  Acme::PM::Dresden:
    file: lib/Acme/PM/Dresden.pm
    version: 0.10
  Acme::PM::Dresden::Acme::Framify:
    file: lib/Acme/PM/Dresden/Acme/Framify.pm
    version: 0.01
  Acme::PM::Dresden::Convert::VQWiki2TWiki:
    file: lib/Acme/PM/Dresden/Convert/VQWiki2TWiki.pm
  Acme::PM::Dresden::TWikiClient:
    file: lib/Acme/PM/Dresden/TWikiClient.pm
  Acme::PM::Dresden::VQWikiClient:
    file: lib/Acme/PM/Dresden/VQWikiClient.pm
generated_by: Module::Build version 0.2611
